name: starseedz
favicon: null
layout_spectrum: 0.9490655744448304
typography_spectrum: 0.1472229694481939
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.35715416073799133
  lightness: 0.1921388457994908
  saturation: 0.04953981074504554
  rhythmicContrast: 0.11580662243068218
purpose: []
