name: starseedz
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1472229694481939
title: Starseedz
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3c4e5a'
    - '#f4f3ef'
    - '#758187'
    - '#9fa7aa'
    - '#b5bbbc'
  brandStrength: 0.6875
  lightness: 0.1921388457994908
  saturation: 0.04953981074504554
  rhythmicContrast: 0.11580662243068218
purpose: []
